<script setup lang="ts">
import yaml from 'js-yaml'

interface Route {
  method: string
  path: string
  description?: string
  tags?: string[]
}

const codeInput = ref(`// Express.js routes
app.get('/api/users', getUsers);
app.post('/api/users', createUser);
app.get('/api/users/:id', getUser);
app.put('/api/users/:id', updateUser);
app.delete('/api/users/:id', deleteUser);

app.get('/api/posts', getPosts);
app.post('/api/posts', createPost);
app.get('/api/posts/:id', getPost);`)

const apiTitle = ref('My API')
const apiVersion = ref('1.0.0')
const apiDescription = ref('API generated by SchemaForge')

const outputFormat = ref<'yaml' | 'json'>('yaml')
const generatedSchema = ref('')
const copySuccess = ref(false)

function parseRoutes(code: string): Route[] {
  const routes: Route[] = []
  
  // Match Express/Fastify patterns
  const patterns = [
    /app\.(get|post|put|delete|patch)\s*\(\s*['"`]([^'"`]+)['"`]/gi,
    /router\.(get|post|put|delete|patch)\s*\(\s*['"`]([^'"`]+)['"`]/gi,
    /\. (get|post|put|delete|patch)\s*\(\s*['"`]([^'"`]+)['"`]/gi,
  ]
  
  for (const pattern of patterns) {
    let match
    while ((match = pattern.exec(code)) !== null) {
      const method = match[1].toUpperCase()
      const path = match[2]
      
      // Skip duplicates
      if (routes.some(r => r.method === method && r.path === path)) continue
      
      routes.push({
        method,
        path,
        description: `${method} ${path}`,
        tags: [path.split('/')[1] || 'default'].filter(Boolean)
      })
    }
  }
  
  return routes
}

function generateOpenAPI(routes: Route[]): object {
  const paths: Record<string, any> = {}
  
  for (const route of routes) {
    if (!paths[route.path]) {
      paths[route.path] = {}
    }
    
    paths[route.path][route.method.toLowerCase()] = {
      summary: route.description,
      description: route.description,
      tags: route.tags,
      responses: {
        '200': {
          description: 'Success',
          content: {
            'application/json': {
              schema: { type: 'object' }
            }
          }
        },
        '400': {
          description: 'Bad Request'
        },
        '401': {
          description: 'Unauthorized'
        },
        '404': {
          description: 'Not Found'
        },
        '500': {
          description: 'Internal Server Error'
        }
      }
    }
    
    // Add request body for POST/PUT/PATCH
    if (['POST', 'PUT', 'PATCH'].includes(route.method)) {
      paths[route.path][route.method.toLowerCase()].requestBody = {
        required: true,
        content: {
          'application/json': {
            schema: { type: 'object' }
          }
        }
      }
    }
    
    // Add path parameters
    const pathParams = route.path.match(/:([a-zA-Z_][a-zA-Z0-9_]*)/g)
    if (pathParams) {
      paths[route.path][route.method.toLowerCase()].parameters = pathParams.map(param => ({
        name: param.substring(1),
        in: 'path',
        required: true,
        schema: { type: 'string' }
      }))
    }
  }
  
  return {
    openapi: '3.0.0',
    info: {
      title: apiTitle.value,
      version: apiVersion.value,
      description: apiDescription.value
    },
    servers: [
      { url: 'http://localhost:3000', description: 'Development' }
    ],
    paths
  }
}

function generate() {
  const routes = parseRoutes(codeInput.value)
  const schema = generateOpenAPI(routes)
  
  generatedSchema.value = outputFormat.value === 'yaml' 
    ? yaml.dump(schema, { indent: 2, lineWidth: -1 })
    : JSON.stringify(schema, null, 2)
}

function copyToClipboard() {
  navigator.clipboard.writeText(generatedSchema.value)
  copySuccess.value = true
  setTimeout(() => { copySuccess.value = false }, 2000)
}

function download() {
  const blob = new Blob([generatedSchema.value], { 
    type: outputFormat.value === 'yaml' ? 'text/yaml' : 'application/json' 
  })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `openapi.${outputFormat.value}`
  a.click()
  URL.revokeObjectURL(url)
}

// Auto-generate on input change
watch([codeInput, apiTitle, apiVersion, apiDescription, outputFormat], () => {
  generate()
})

onMounted(() => {
  generate()
})

useHead({
  title: 'SchemaForge - API Schema Generator',
  meta: [
    { name: 'description', content: 'Generate OpenAPI schemas from your code automatically' }
  ]
})
</script>

<template>
  <div class="app">
    <header class="header">
      <div class="logo">
        <span class="logo-icon">⚒️</span>
        <div class="logo-text">
          <h1>SchemaForge</h1>
          <span class="subtitle">API Schema Generator</span>
        </div>
      </div>
      <div class="header-actions">
        <a href="https://github.com" target="_blank" class="github-link">GitHub</a>
      </div>
    </header>

    <main class="main">
      <section class="hero">
        <h2>Generate OpenAPI schemas from your code</h2>
        <p>Paste your route definitions, get complete OpenAPI specs in seconds.</p>
      </section>

      <div class="config-bar">
        <div class="config-group">
          <label>API Title</label>
          <input v-model="apiTitle" type="text" placeholder="My API" />
        </div>
        <div class="config-group">
          <label>Version</label>
          <input v-model="apiVersion" type="text" placeholder="1.0.0" />
        </div>
        <div class="config-group">
          <label>Format</label>
          <select v-model="outputFormat">
            <option value="yaml">YAML</option>
            <option value="json">JSON</option>
          </select>
        </div>
      </div>

      <div class="editor-grid">
        <div class="editor-panel">
          <div class="panel-header">
            <h3>📝 Route Definitions</h3>
            <span class="hint">Express, Fastify, Hono patterns supported</span>
          </div>
          <textarea 
            v-model="codeInput" 
            class="code-input"
            placeholder="Paste your route definitions here..."
            spellcheck="false"
          ></textarea>
        </div>

        <div class="editor-panel">
          <div class="panel-header">
            <h3>📄 Generated Schema</h3>
            <div class="panel-actions">
              <button @click="copyToClipboard" class="btn-small" :class="{ success: copySuccess }">
                {{ copySuccess ? '✓ Copied!' : '📋 Copy' }}
              </button>
              <button @click="download" class="btn-small">⬇ Download</button>
            </div>
          </div>
          <textarea 
            :value="generatedSchema" 
            class="code-output"
            readonly
            spellcheck="false"
          ></textarea>
        </div>
      </div>

      <section class="features">
        <h3>Features</h3>
        <div class="feature-grid">
          <div class="feature">
            <span class="feature-icon">⚡</span>
            <h4>Instant Generation</h4>
            <p>Parse routes in real-time, see results immediately</p>
          </div>
          <div class="feature">
            <span class="feature-icon">📦</span>
            <h4>OpenAPI 3.0</h4>
            <p>Industry-standard specification format</p>
          </div>
          <div class="feature">
            <span class="feature-icon">🔄</span>
            <h4>Multiple Formats</h4>
            <p>Export as YAML or JSON</p>
          </div>
          <div class="feature">
            <span class="feature-icon">🆓</span>
            <h4>Free to Use</h4>
            <p>No signup required, works in your browser</p>
          </div>
        </div>
      </section>

      <section class="pricing">
        <h3>Pricing</h3>
        <div class="pricing-grid">
          <div class="pricing-card">
            <h4>Free</h4>
            <div class="price">$0<span>/mo</span></div>
            <ul>
              <li>✓ Unlimited generations</li>
              <li>✓ YAML & JSON export</li>
              <li>✓ All frameworks</li>
            </ul>
          </div>
          <div class="pricing-card featured">
            <div class="badge">Pro</div>
            <h4>Pro</h4>
            <div class="price">$19<span>/mo</span></div>
            <ul>
              <li>✓ Everything in Free</li>
              <li>✓ Save schemas</li>
              <li>✓ API client generation</li>
              <li>✓ Custom themes</li>
            </ul>
          </div>
          <div class="pricing-card">
            <h4>Team</h4>
            <div class="price">$49<span>/mo</span></div>
            <ul>
              <li>✓ Everything in Pro</li>
              <li>✓ Team workspace</li>
              <li>✓ Collaboration</li>
              <li>✓ Priority support</li>
            </ul>
          </div>
        </div>
      </section>
    </main>

    <footer class="footer">
      <p>Built with Vue 3 + Nuxt 3 • MIT License • <a href="https://github.com" target="_blank">View Source</a></p>
    </footer>
  </div>
</template>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

:root {
  --primary: #f59e0b;
  --primary-dark: #d97706;
  --bg: #0c0f14;
  --bg-elevated: #141820;
  --bg-card: #1a1f2a;
  --text: #f8fafc;
  --text-muted: #94a3b8;
  --border: #2a3140;
  --success: #22c55e;
  --accent: #8b5cf6;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: var(--bg);
  color: var(--text);
  min-height: 100vh;
  line-height: 1.6;
}

.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

/* Header */
.header {
  background: var(--bg-elevated);
  border-bottom: 1px solid var(--border);
  padding: 1rem 2rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.logo {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.logo-icon {
  font-size: 2rem;
}

.logo-text h1 {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--primary);
}

.subtitle {
  color: var(--text-muted);
  font-size: 0.8rem;
}

.github-link {
  color: var(--text-muted);
  text-decoration: none;
  font-size: 0.9rem;
}

.github-link:hover {
  color: var(--text);
}

/* Main */
.main {
  flex: 1;
  padding: 2rem;
  max-width: 1400px;
  margin: 0 auto;
  width: 100%;
}

.hero {
  text-align: center;
  margin-bottom: 2rem;
}

.hero h2 {
  font-size: 2rem;
  margin-bottom: 0.5rem;
}

.hero p {
  color: var(--text-muted);
  font-size: 1.1rem;
}

/* Config Bar */
.config-bar {
  display: flex;
  gap: 1rem;
  margin-bottom: 1.5rem;
  flex-wrap: wrap;
}

.config-group {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.config-group label {
  font-size: 0.75rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.config-group input,
.config-group select {
  padding: 0.5rem 0.75rem;
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 0.5rem;
  color: var(--text);
  font-size: 0.9rem;
  min-width: 150px;
}

.config-group input:focus,
.config-group select:focus {
  outline: none;
  border-color: var(--primary);
}

/* Editor Grid */
.editor-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
  margin-bottom: 3rem;
}

.editor-panel {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 0.75rem;
  overflow: hidden;
}

.panel-header {
  padding: 0.75rem 1rem;
  background: var(--bg-elevated);
  border-bottom: 1px solid var(--border);
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.panel-header h3 {
  font-size: 0.9rem;
  font-weight: 600;
}

.hint {
  font-size: 0.75rem;
  color: var(--text-muted);
}

.panel-actions {
  display: flex;
  gap: 0.5rem;
}

.btn-small {
  padding: 0.35rem 0.75rem;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 0.375rem;
  color: var(--text);
  font-size: 0.8rem;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-small:hover {
  background: var(--border);
}

.btn-small.success {
  background: var(--success);
  border-color: var(--success);
  color: white;
}

.code-input,
.code-output {
  width: 100%;
  min-height: 400px;
  padding: 1rem;
  background: var(--bg);
  border: none;
  color: var(--text);
  font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
  font-size: 0.85rem;
  line-height: 1.5;
  resize: vertical;
}

.code-input:focus,
.code-output:focus {
  outline: none;
}

.code-output {
  background: #0a0d10;
}

/* Features */
.features {
  margin-bottom: 3rem;
}

.features h3 {
  text-align: center;
  margin-bottom: 1.5rem;
  font-size: 1.5rem;
}

.feature-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1.5rem;
}

.feature {
  text-align: center;
  padding: 1.5rem;
}

.feature-icon {
  font-size: 2.5rem;
  display: block;
  margin-bottom: 0.75rem;
}

.feature h4 {
  font-size: 1.1rem;
  margin-bottom: 0.5rem;
}

.feature p {
  color: var(--text-muted);
  font-size: 0.9rem;
}

/* Pricing */
.pricing {
  margin-bottom: 3rem;
}

.pricing h3 {
  text-align: center;
  margin-bottom: 1.5rem;
  font-size: 1.5rem;
}

.pricing-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1.5rem;
  max-width: 900px;
  margin: 0 auto;
}

.pricing-card {
  background: var(--bg-card);
  border: 1px solid var(--border);
  border-radius: 1rem;
  padding: 2rem;
  text-align: center;
  position: relative;
}

.pricing-card.featured {
  border-color: var(--primary);
  transform: scale(1.05);
}

.pricing-card .badge {
  position: absolute;
  top: -0.75rem;
  left: 50%;
  transform: translateX(-50%);
  background: var(--primary);
  color: var(--bg);
  padding: 0.25rem 1rem;
  border-radius: 1rem;
  font-size: 0.75rem;
  font-weight: 600;
}

.pricing-card h4 {
  font-size: 1.25rem;
  margin-bottom: 0.5rem;
}

.price {
  font-size: 2.5rem;
  font-weight: 700;
  color: var(--primary);
  margin-bottom: 1.5rem;
}

.price span {
  font-size: 1rem;
  color: var(--text-muted);
  font-weight: 400;
}

.pricing-card ul {
  list-style: none;
  text-align: left;
}

.pricing-card li {
  padding: 0.5rem 0;
  color: var(--text-muted);
  font-size: 0.9rem;
}

/* Footer */
.footer {
  background: var(--bg-elevated);
  border-top: 1px solid var(--border);
  padding: 1.5rem 2rem;
  text-align: center;
  color: var(--text-muted);
  font-size: 0.875rem;
}

.footer a {
  color: var(--primary);
  text-decoration: none;
}

@media (max-width: 768px) {
  .header { padding: 1rem; }
  .main { padding: 1rem; }
  
  .editor-grid {
    grid-template-columns: 1fr;
  }
  
  .code-input,
  .code-output {
    min-height: 250px;
  }
  
  .pricing-card.featured {
    transform: none;
  }
}
</style>
